server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?userUnicode=true&characterEncoding=utf-8&timeServerZone=Asia/Shanghai
    username: root
    password: 116924
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 300ms

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  tokenHeader: Authorization
  tokenHead: 'Bearer '
  expiration: 86400
  secret: mySecretMySecretMySecretMySecretMySecretMySecretMySecretMySecretMySecretMySecretMySecretMySecretMySecretMySecretMySecretMySecret

security:
  ignore:
    urls:
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload

redis:
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resource'
  expiration:
    common: 86400
